### ISSUE TITLE
Long running test intermittently fails with Resource Not Found

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/radius#7088]
Very frequently long running test fails with logs.
It occurs during terraform recipe deployment "Couldn’t find the blob storage container resource for while creating blob storage."

https://github.com/radius-project/radius/actions/runs/7655626377/job/20862163886

[AB#11012](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11012)

**Comment by youngbupark** [comment]
@ytimocin I wonder if the test images are being deleted while purging old images - https://github.com/radius-project/radius/actions/workflows/purge-test-resources.yaml

**Comment by ytimocin** [comment]
I was thinking that this could be due to an Azure resource not being ready as the test runs:

`"terraform apply failure: exit status 1\n\nError: failed creating container: failed creating container: containers.Client#Create: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The specified resource does not exist.\\nRequestId:79d66c4e-901e-001c-7898-4fff09000000\\nTime:2024-01-25T14:10:39.7340262Z\"\n\n  with module.default.azurerm_storage_container.test_container,\n  on .terraform/modules/default/main.tf line 18, in resource \"azurerm_storage_container\" \"test_container\":\n  18: resource \"azurerm_storage_container\" \"test_container\" {\n\n"`

**Comment by ytimocin** [comment]
There is an issue that tracks this btw: https://github.com/radius-project/radius/issues/7060. Can you check if this is the same error as you see @nithyatsu?

**Comment by nithyatsu** [comment]
yes, thank you. closing as dup.
