### ISSUE TITLE
Unable to rad init with v0.33.0

### ISSUE THREAD

**Issue by superbeeny** [radius-project/radius#7561]
### Steps to reproduce

1. Uninstall v0.32.0
2. Install v.0.33.0
3. Execute `rad init`

### Observed behavior

```sh
➜   ✗ rad init
Unable to verify Radius installation. Cause: Kubernetes cluster unreachable: no Auth Provider found for name "oidc".

➜   ✗ rad version
RELEASE   VERSION   BICEP     COMMIT
0.33.0    v0.33.0   0.33.0    6ffdc9980420c00f7af35b024dd0e62e598efef2
```

### Desired behavior

Radius should initialize the cluster

### rad Version

RELEASE   VERSION   BICEP     COMMIT
0.33.0    v0.33.0   0.33.0    6ffdc9980420c00f7af35b024dd0e62e598efef2

### Operating system

macOS Sonoma 14.4.1 M1

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12242](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12242)

**Comment by rynowak** [comment]
I think this is failing because we failed to register the OIDC auth provider in the `rad` cli.

Here's an example of a similar bug: https://github.com/kubernetes/client-go/issues/345

We already do this for our controller (all auth plugins) right here: https://github.com/radius-project/radius/blob/main/cmd/controller/main.go#L27

I think the right home would be where we initialize the Kubernetes client in the CLI: https://github.com/radius-project/radius/blob/main/pkg/cli/kubernetes/kubernetes.go

Interested in sending us a PR?

**Comment by superbeeny** [comment]
Sure :)
