### ISSUE TITLE
Running Radius on AKS Automatic causes Node failures

### ISSUE THREAD

**Issue by loekd** [radius-project/radius#7676]
### Steps to reproduce

- Deploy Radius to AKS Automatic
- Deploy workload
- Scale workload to many instances

### Observed behavior

- After some time, nodes from the node pool will crash
- 
![image](https://github.com/radius-project/radius/assets/12125836/030e5f5f-daa6-421f-806c-a25baa5cf38b)
![image](https://github.com/radius-project/radius/assets/12125836/2db519b5-6b34-49a8-b81f-062f10e35ba1)

- They recover after some time

### Desired behavior

- No node crashes

### Workaround

- No workaround
- Does not happen when running workloads without Radius

### rad Version

```
RELEASE   VERSION   BICEP     COMMIT
0.34.0    v0.34.0   0.34.0    0fd82e7eaa9388fead4ea76cb9137ba2a225a236
```

### Operating system

Ubuntu (default node)

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12487](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12487)

**Comment by rynowak** [comment]
The likely cause of this is that the UCP APIServer Extension went down. We're using a Kubernetes extensibility point that's pretty heavyweight, and can cause issues like this. The reasons why we chose that approach aren't really true any more and we should migrate away.

A better approach would be for us to port-forward to the control-plane instead of exposing it through the API Server. This would still require the user to have Kubernetes credentials (that's good) but would also be more flexible because users could expose the control-plane in whatever manner they like.

**Comment by rynowak** [comment]
> A better approach would be for us to port-forward to the control-plane instead of exposing it through the API Server. This would still require the user to have Kubernetes credentials (that's good) but would also be more flexible because users could expose the control-plane in whatever manner they like.

@brooke-hamilton - if you're interested in learning more about this approach, this is what the ArgoCD CLI does. Argo's control-plane is running inside the cluster, and (by default) they port-forward so the CLI can talk to it. https://github.com/argoproj/argo-cd/blob/master/pkg/apiclient/apiclient.go#L206

**Comment by brooke-hamilton** [comment]
I opened this issue as related. https://github.com/Azure/AKS/issues/4513.

**Comment by brooke-hamilton** [comment]
I believe this behavior is not related to Radius specifically. I was able to reproduce node crashes by deploying a single pod to an AKS auto cluster and scaling it up to 100 instances. @loekd please comment if there is any other context we should consider. Thank you for reporting the issue! 🚀
